### ISSUE TITLE
optional int32 value may not be 0

### ISSUE THREAD

**Issue by sab24** [drslump/Protobuf-PHP#25] opened 2012-12-15 15:26 UTC
Hi,

I've found a problem today. I have a proto file like the following:

Package stream;

Message User{
     optional int32 userid = 1;
     optional string name = 2;
}
Message Other{
     optional string one = 1;
     optional string two = 2;
}

Message Container{
     required string header = 1;
     repeated User user = 2;
     repeated Other other = 3;
}

php-file:
$header0 = new stream\User();
$header0->userid = "0";
$header0->name = "testuser";

$header1 = new stream\Other();
$header1->one = "one";
$header1->two = "two";

$container = new stream\Container();
$container->setHeader("page1");
$container->addUser($header0);
$container->addUser($header1);

When I set userid to 0 like above, my c++ application sees only a message Container with one message user, where the values of Other are not somehow getting lost. If I set userid to any other value than 0 it does work. Is this a limitation of protobuffers in general or is this a bug?

**Comment by drslump** [comment] 2012-12-17 16:24
It's not a limitation of protocol buffers, integer values can have a value of 0.

A couple of questions, are you using the pear package, the master branch or the lazy branch of Protobuf-PHP? what library are you using in the c++ side?

**Comment by sab24** [comment] 2012-12-18 18:57
I have the version from PEAR. It says const VERSION = '0.9.4'; in DrSlump/protobuf.php. I have downloaded it within the last month, so I think it is the newest version. I am using the libraries from Google developer website. I use protobuf 2.4 for compiling the c++ headers.

**Comment by sab24** [comment] 2012-12-31 09:50
I am having more problems, which may be related to the problem above. I have now tried the lazy branch, I tried to update my proto file to use strings only, I tried bytes only, and I have tried a different protobuf version for c++, 2.5.0rc1. It didn't work. I now have displayed everything to the screen.

When using c++ to generate a stream I get this at the receiving end when displaying in plaintext:

page1user2
ace1Home
01-01-2012"

The data is processed in the server as:
racenamerace1
locationHome
date01-01-2012

With php I get this when I echo the data to the screen in the php application with echo:
  page1user"*2:2 race1Home 01-01-2012"

In the c++ app this is seen as:
page1user"*2:2
ace1Home
01-01-2012"

With php as a client I get raceproperties_size is 0, with the c++ client I get raceproperties size is 1. 

I tried encoding everything to utf8, and it didn't work. Here is the source code for php:

<?php
set_include_path('/public_html/PEAR/PEAR/');
require_once 'DrSlump/Protobuf.php';
\DrSlump\Protobuf::autoload();
include_once **DIR** . '/build/stream.php';

function transfer($st){ //transfer function, should work
    $socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
    $return = socket_connect($socket, '172.28.1.3', '1100');

```
$i = 0;
$length = strlen($st);
$stPart=str_split($st,8192);
$parts = round (($length/8192));
if ($length > 8192){ //in chunks
    while ($i < $parts){
        $sent = socket_write($socket, $stPart[$i], $length);
        $i++;
    }
}
else{ // message sent at once
    $sent = socket_write($socket, $st, $length);
}
while($bytes = socket_recv($socket, $receive, 2048,0)){
    echo $receive;
}
//if (false !== ($bytes = socket_recv($socket, $buf, 2048, MSG_WAITALL)))
//if( $receive !== 'ack'){echo 'error on ack';}
socket_close ($socket);
```

}

$container = new stream\Container();
    if (!empty($_POST["racename"]) || !empty($_POST["location"]) || !empty($_POST["date"]) || !empty($_POST["racepropertiesnotes"])){
        echo ("one raceproperties received");
        $header6 = new stream\Raceproperties();
        $header6->racename = utf8_encode($_POST["racename"]);
        $header6->location = utf8_encode($_POST["location"]);
        $header6->date = utf8_encode($_POST["date"]);
        $header6->racepropertiesnotes = utf8_encode($_POST["racepropertiesnotes"]);
        $container->addRaceproperties($header6);
    }
$data = $container->serialize();
transfer ($data);
echo $data;
?>

stream.proto:
package stream;

message Header{//for page request
    optional string page = 1;
    optional string username = 2;
    optional int32 raceidentifier = 3;
    optional bool signup = 4;//signing up with the data of memberid and raceid
    optional int32 participantidentifier = 5;
    optional string command = 6;  
    optional string ipaddress = 7;
}

message Members{//for editting members, the table where the data comes from does not contain male female, thats why its being send to client and back
    optional int32 memberid = 1;
    optional string membername = 2;
    optional bool ismale = 3;
    optional string dateofbirth = 4;
}

message Participants{//information about the participant
    optional int32 userid = 1;
    optional int32 matchid = 2;
    optional int32 classid = 3;
    optional string endposition = 4;
    optional string endtime = 5;
    optional string participantnotes = 6;
}

message Races{
    optional string name = 1;
    optional string racetypeid = 2;
}

message Racetypes{
    optional string racetypename = 1;
}

message Raceproperties{//information about the race
    optional string racename = 1;
    optional string location = 2;
    optional string date = 3;
    optional string racepropertiesnotes = 4;
}

message Classproperties{//information about the race's categories of participants
    optional string raceid = 1;
    optional bool malecategory = 2; //if male then true, if women then false
    optional string classname = 3;
    optional string distance = 4;
}

message Datamessage{ //for binary data
    optional string filename = 1;
    optional bytes data = 2;
}

message Container{//the message that is the parent of all
    required Header header = 1;
    repeated Members member = 2;
    repeated Participants participant = 3;
    repeated Races races = 4;
    repeated Racetypes racetype = 5;
    repeated Raceproperties raceproperties = 6;
    repeated Classproperties classproperties = 7;
    repeated Datamessage datamessage = 8;
}

c++:
stream::Container container;
container.ParseFromString(buffer); //buffer comes from a socket
std::cout << "raceproperties_size" << container.raceproperties_size()       << std::endl;

c++ output:
raceproperties_size0

Hex codes with text:

c++ client:
a d a 5 70 61 67 65 31 12 4 75 73 65 72 32 1b a 5 72 61 63 65 31 12 4 48 6f 6d 65 1a a 30 31 2d 30 31 2d 32 30 31 32 22 0 

  p a g e 1   u s e r 2 
  r a c e 1   H o m e  
 0 1 - 0 1 - 2 0 1 2 " 

php client:
a 15 a 5 70 61 67 65 31 12 4 75 73 65 72 22 0 2a 0 32 0 3a 0 32 1b a 5 72 61 63 65 31 12 4 48 6f 6d 65 1a a 30 31 2d 30 31 2d 32 30 31 32 22 0 

  p a g e 1   u s e r "  \*  2  :  2 
  r a c e 1   H o m e  
 0 1 - 0 1 - 2 0 1 2 " 

var_dump of container:

vardump of container:
object(stream\Container)#2 (11) { ["header"]=> object(stream\Header)#13 (10) { ["page"]=> string(5) "page1" ["username"]=> string(4) "user" ["raceidentifier"]=> NULL ["signup"]=> string(0) "" ["participantidentifier"]=> string(0) "" ["command"]=> string(0) "" ["ipaddress"]=> string(0) "" ["_descriptor":protected]=> object(DrSlump\Protobuf\Descriptor)#14 (4) { ["class":protected]=> string(13) "stream\Header" ["name":protected]=> string(13) "stream.Header" ["fields":protected]=> array(7) { [1]=> object(DrSlump\Protobuf\Field)#15 (8) { ["number"]=> int(1) ["name"]=> string(4) "page" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [2]=> object(DrSlump\Protobuf\Field)#16 (8) { ["number"]=> int(2) ["name"]=> string(8) "username" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [3]=> object(DrSlump\Protobuf\Field)#17 (8) { ["number"]=> int(3) ["name"]=> string(14) "raceidentifier" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [4]=> object(DrSlump\Protobuf\Field)#18 (8) { ["number"]=> int(4) ["name"]=> string(6) "signup" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [5]=> object(DrSlump\Protobuf\Field)#19 (8) { ["number"]=> int(5) ["name"]=> string(21) "participantidentifier" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [6]=> object(DrSlump\Protobuf\Field)#20 (8) { ["number"]=> int(6) ["name"]=> string(7) "command" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [7]=> object(DrSlump\Protobuf\Field)#21 (8) { ["number"]=> int(7) ["name"]=> string(9) "ipaddress" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } } ["names":protected]=> array(0) { } } ["_extensions":protected]=> array(0) { } ["_unknown":protected]=> array(0) { } } ["member"]=> array(0) { } ["participant"]=> array(0) { } ["races"]=> array(0) { } ["racetype"]=> array(0) { } ["raceproperties"]=> array(1) { [0]=> object(stream\Raceproperties)#22 (7) { ["racename"]=> string(5) "race1" ["location"]=> string(4) "Home" ["date"]=> string(10) "01-01-2012" ["racepropertiesnotes"]=> string(0) "" ["_descriptor":protected]=> object(DrSlump\Protobuf\Descriptor)#23 (4) { ["class":protected]=> string(21) "stream\Raceproperties" ["name":protected]=> string(21) "stream.Raceproperties" ["fields":protected]=> array(4) { [1]=> object(DrSlump\Protobuf\Field)#24 (8) { ["number"]=> int(1) ["name"]=> string(8) "racename" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [2]=> object(DrSlump\Protobuf\Field)#25 (8) { ["number"]=> int(2) ["name"]=> string(8) "location" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [3]=> object(DrSlump\Protobuf\Field)#26 (8) { ["number"]=> int(3) ["name"]=> string(4) "date" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [4]=> object(DrSlump\Protobuf\Field)#27 (8) { ["number"]=> int(4) ["name"]=> string(19) "racepropertiesnotes" ["type"]=> int(12) ["rule"]=> int(1) ["reference"]=> NULL ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } } ["names":protected]=> array(0) { } } ["_extensions":protected]=> array(0) { } ["_unknown":protected]=> array(0) { } } } ["classproperties"]=> array(0) { } ["datamessage"]=> array(0) { } ["_descriptor":protected]=> object(DrSlump\Protobuf\Descriptor)#4 (4) { ["class":protected]=> string(16) "stream\Container" ["name":protected]=> string(16) "stream.Container" ["fields":protected]=> array(8) { [1]=> object(DrSlump\Protobuf\Field)#5 (8) { ["number"]=> int(1) ["name"]=> string(6) "header" ["type"]=> int(11) ["rule"]=> int(2) ["reference"]=> string(14) "\stream\Header" ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [2]=> object(DrSlump\Protobuf\Field)#6 (8) { ["number"]=> int(2) ["name"]=> string(6) "member" ["type"]=> int(11) ["rule"]=> int(3) ["reference"]=> string(15) "\stream\Members" ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [3]=> object(DrSlump\Protobuf\Field)#7 (8) { ["number"]=> int(3) ["name"]=> string(11) "participant" ["type"]=> int(11) ["rule"]=> int(3) ["reference"]=> string(20) "\stream\Participants" ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [4]=> object(DrSlump\Protobuf\Field)#8 (8) { ["number"]=> int(4) ["name"]=> string(5) "races" ["type"]=> int(11) ["rule"]=> int(3) ["reference"]=> string(13) "\stream\Races" ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [5]=> object(DrSlump\Protobuf\Field)#9 (8) { ["number"]=> int(5) ["name"]=> string(8) "racetype" ["type"]=> int(11) ["rule"]=> int(3) ["reference"]=> string(17) "\stream\Racetypes" ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [6]=> object(DrSlump\Protobuf\Field)#10 (8) { ["number"]=> int(6) ["name"]=> string(14) "raceproperties" ["type"]=> int(11) ["rule"]=> int(3) ["reference"]=> string(22) "\stream\Raceproperties" ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [7]=> object(DrSlump\Protobuf\Field)#11 (8) { ["number"]=> int(7) ["name"]=> string(15) "classproperties" ["type"]=> int(11) ["rule"]=> int(3) ["reference"]=> string(23) "\stream\Classproperties" ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } [8]=> object(DrSlump\Protobuf\Field)#12 (8) { ["number"]=> int(8) ["name"]=> string(11) "datamessage" ["type"]=> int(11) ["rule"]=> int(3) ["reference"]=> string(19) "\stream\Datamessage" ["default"]=> NULL ["packed"]=> bool(false) ["extension"]=> bool(false) } } ["names":protected]=> array(0) { } } ["_extensions":protected]=> array(0) { } ["_unknown":protected]=> array(0) { } }

**Comment by drslump** [comment] 2013-10-13 12:39
First of all allow me to apologize for the very late response. I've been trying to reproduce the issue but couldn't. I did notice in the original post an issue, perhaps a typo?, with how the container was being constructed:

```
$container->addUser($header0);
$container->addUser($header1);  # This should be ->addOther($header1)
```

Since it's been a long time, I'm going to close this issue. Sorry for any inconvenience.

**Closed as completed by drslump** 2013-10-13 12:39 UTC
